version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .