site_name: anixart
repo_url: https://github.com/SantaSpeen/anixart
site_author: Maxim Khomutov
remote_name: master
use_directory_urls: true

nav:
    - Введение: index.md
    - Общая информация:
        Быстрое начало: home/index.md
        Примеры использования: home/examples.md
    - API библиотеки:
        Введение: LibApi/index.md
        Метки и условные обозначения: LibApi/tags.md
        Методы: LibApi/methods.md
        Неописанные методы: LibApi/todo_methods.md
    - API Anixart:
        Введение: anixApi/index.md
        Auth: anixApi/auth.md
        Profile: anixApi/profile.md
        Collections: anixApi/collections.md
        Release: anixApi/release.md
        Other: anixApi/other.md

    - CHANGELOG: CHANGELOG.md
    - Обратная связь: callback.md

theme:
  name: material
  locale: ru
  highlightjs: true
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Включить ночную тему.
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Включить дневную тему.

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
